version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/hackthon
permissions:
  - object: /home/ubuntu/
    pattern: "**"
    owner: ubuntu
    group: ubuntu
hooks:
  BeforeInstall:
    - location: scripts/clean_instance.sh
      timeout: 600
      runas: root
  AfterInstall:
    - location: scripts/install_os_dependencies.sh
      timeout: 600
      runas: root
    - location: scripts/install_python_dependencies.sh
      timeout: 600
      runas: root
    - location: scripts/ngnix.sh
      timeout: 600
      runas: root
    - location: scripts/migrate.sh
      timeout: 600
      runas: root
